#include <stdio.h>
#include <string.h>

#include <errno.h>

#include "src/alloc.h"
#include "src/gen.h"
#include "src/lexer.h"
#include "src/state.h"
#include "src/utils.h"

#define SH_AUTHOR   "Wal FE"
#define SH_VERSION  "0.01"

static char *loadfile (const char *filename) {
    FILE *file = fopen(filename, "rb");

    if (!file) {
        sh_error("%s: %s", filename, strerror(errno));
    }

    fseek(file, 0, SEEK_END);
    sh_size size = ftell(file);
    fseek(file, 0, SEEK_SET);
    char *buffer = sh_malloc(size+1);
    fread(buffer, 1, size, file);
    fclose(file);

    /* if there are some zero bytes in file */
    for (sh_size i = 0; i < size; i++) {
        if (buffer[i] == '\0') buffer[i] = ' ';
    }

    buffer[size] = '\0';

    return buffer;
}

static void print_help (void) {
    errorf("bytecode - prints generated bytecode\n");
    errorf("info - prints info about Short Programming Language\n");
    errorf("help - prints this message\n");
    errorf("run - runs a program in Short\n");
}

static void print_info (void) {
    errorf("Short Programming Language Beta\n");
    errorf("Author: " SH_AUTHOR ", Github: github.com/walfestelist\n");
    errorf("Version: " SH_VERSION "\n");
}

static const char *handle_args (int argc, char **argv) {
    if (argc < 2) {
        print_help();
        sh_error("too little arguments");
    }
    if (argc == 2) {
        if (strcmp(argv[1], "help") == 0) print_help();
        else if (strcmp(argv[1], "info") == 0) print_info();
        else if (
                strcmp(argv[1], "run") == 0 || 
                strcmp(argv[1], "bytecode") == 0
                ) {
            sh_error("filename expected");
        }
        else {
            print_help();
            sh_error("unknown option: %s", argv[1]);
        }

        return NULL;
    }

    if (argc == 3) {
        if (
                strcmp(argv[1], "run") == 0 || 
                strcmp(argv[1], "bytecode") == 0
            ) {
            return argv[2];
        } else {
            print_help();
            sh_error("unknown option: %s", argv[1]);
        }
    }

    sh_error("too much arguments");
    print_help();
}

int main (int argc, char **argv) {
    const char *filename = handle_args(argc, argv);
    if (!filename) return 0;
    char *src = loadfile(filename);
    struct sh_lexer L = sh_lex(src);
    struct sh_bc bc = sh_gen(&L);

    sh_free(src);
    return 0;
}
